import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Layout.module.css';

const menuItens = [
    {
        texto: 'Sobre Nós',
        link: '#',
    },
    {
        texto: 'Intercâmbio',
        link: '#',
    },
    {
        texto: 'Lazer',
        link: '#',
    },
];

const Layout: NextPage = ({ children }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Turismo</title>
                {/*
                <meta name="description" content="Generated by create next app" />
                */}
                
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Contem a imagem com nuvens que passa pela tela no fundo da página */}
            <div id={styles.fundo} />

            <div id={styles.barra}>
                <div id={styles.logoContainer}>
                    <img src="/res/logo.png" width="150" height="30" />
                </div>

                <div id={styles.barraMenu}>
                    <ul>
                        {menuItens.map((item, i) => (
                            <li key={i}>
                                <a href={item.link}>{item.texto}</a>
                            </li>
                        ))}
                    </ul>
                </div>
            </div>

            {children}
        </div>
    );
};

export default Layout;